export const LOGIN_START = 'LOGINING_START';
export const LOGIN_END = 'LOGINING_END';
export const LOGIN_CLEAN = 'LOGIN_CLEAN';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_END = 'DASHBOARD_END';
export const DASHBOARD_CLEAN = 'DASHBOARD_CLEAN';



export const REGIONS_START = 'REGIONS_START';
export const REGIONS_END = 'REGIONS_END';

export const CITIES_START = 'CITIES_START';
export const CITIES_END = 'CITIES_END';

export const SCHOOLS_START = 'SCHOOLS_START';
export const SCHOOLS_END = 'SCHOOLS_END';

export const FETCH_DASHBOARD_DATA_START = 'FETCH_DASHBOARD_DATA_START';
export const FETCH_DASHBOARD_DATA_END = 'FETCH_DASHBOARD_DATA_END';
