export const REGISTER_START = "REGISTERING_START";
export const REGISTER_END = "REGISTERING_END";
export const REGISTER_CLEAN = "REGISTER_CLEAN";
export const FORGOT_PASSWORD_REQUEST_START = "FORGOT_PASSWORD_REQUEST_START";
export const FORGOT_PASSWORD_REQUEST_END = "FORGOT_PASSWORD_REQUEST_END";